### ISSUE TITLE
The set up tutorial on PSK1.2.2 leads to errors on build

### ISSUE THREAD

**Issue by greenido** [Polymer/polymer#3306]
How to reproduce:
1. Install [PSK1.2.2](https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.2.2/polymer-starter-kit-light-1.2.2.zip)
2. Follow the steps: https://www.polymer-project.org/1.0/docs/start/psk/set-up.html
3. When you reach the 'gulp' phase you should get:
```
idog (master) poly-news-1 $ gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/through2/through2.js:1:79)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

idog (master) poly-news-1 $ node -v
v5.0.0
idog (master) poly-news-1 $ npm -v
3.5.3
```

Thanks!

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/polymer-starter-kit#659
