### ISSUE TITLE
Issue on following the step by step guide on https://www.polymer-project.org/1.0/docs/start/psk/set-up.html

### ISSUE THREAD

**Issue by RiccardoCereghino** [Polymer/polymer#3583]
#### Steps to Reproduce

Follow the guide on the polymer-project to set up psk
https://www.polymer-project.org/1.0/docs/start/psk/set-up.html

Build and serve step 2

`gulp 
`

#### Expected Results

No error is throw
#### Actual Results
```
[x@x x]$ gulp
[13:10:09] Using gulpfile ~/x/gulpfile.js
[13:10:09] Starting 'clean'...
[13:10:09] Finished 'clean' after 6.81 ms
[13:10:09] Starting 'default'...
[13:10:09] Starting 'ensureFiles'...
[13:10:09] 'ensureFiles' errored after 280 μs
[13:10:09] Error: Missing Required Files
/home/r/x/.bowerrc Not Found
    at ensureFiles (/home/r/x/tasks/ensure-files.js:24:15)
    at Gulp.<anonymous> (/home/r/x/gulpfile.js:113:3)
    at module.exports (/home/r/x/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/r/x/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/r/x/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/r/x/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/r/x/node_modules/run-sequence/index.js:88:16)
    at runSequence (/home/r/x/node_modules/run-sequence/index.js:99:2)
    at Gulp.<anonymous> (/home/r/x/gulpfile.js:272:3)
    at module.exports (/home/r/x/node_modules/orchestrator/lib/runTask.js:34:7)
[13:10:09] 'default' errored after 3.96 ms
[13:10:09] Error in plugin 'run-sequence'
Message:
    An error occured in task 'ensureFiles'.

```
### Versions

- Polymer Starter Kit: v1.3.0
- Polymer: v1.0.0
- webcomponents: v0.7.21
- gulp: CLI version 3.9.1
- npm: v3.8.3
- node: v5.10.1
- fedora: 23

**Comment by RiccardoCereghino** [comment]
wrong repository
