### ISSUE TITLE
Error when installing the PSK

### ISSUE THREAD

**Issue by AndreasEK** [Polymer/polymer#3623]
I've just tried to get started with the PSK (polymer-starter-kit-1.3.0), but it doesn't work for me. Since I am rather new to the whole npm/node/bower world, I have no clue how to debug that atm. When I just run "gulp serve", I am getting an empty page on http://localhost:5000/

Andreass-MacBook-Pro:psk aek$ gulp
(node:11846) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[17:38:36] Using gulpfile ~/Development/psk/gulpfile.js
[17:38:36] Starting 'clean'...
[17:38:36] Finished 'clean' after 8.85 ms
[17:38:36] Starting 'default'...
[17:38:36] Starting 'ensureFiles'...
[17:38:36] Finished 'ensureFiles' after 191 μs
[17:38:36] Starting 'copy'...
[17:38:36] Starting 'styles'...
[17:38:36] styles all files 120 B
[17:38:36] Finished 'styles' after 353 ms
[17:38:36] copy all files 1.11 MB
[17:38:36] Finished 'copy' after 429 ms
[17:38:36] Starting 'images'...
[17:38:37] Starting 'fonts'...
[17:38:37] Starting 'html'...
[17:38:37] Finished 'fonts' after 138 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at semicolon (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2060:56)
    at simple_statement (eval at <anonymous> (/Users/aek/Development/psk/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2240:73)

Andreass-MacBook-Pro:psk aek$ node --version
v6.0.0
Andreass-MacBook-Pro:psk aek$ npm --version
3.8.6
Andreass-MacBook-Pro:psk aek$ bower --version
1.7.9

**Comment by Pablo-Ivan** [comment]
Try deleting all what you installed and reinstall it from bower. The new version shoukd work. If not, I recommend using some kind of cloud IDE like cloud9, which is actually good at handling dependencies.

**Comment by TimvdLippe** [comment]
The PSK has since been updated to Polymer 2 and ES6. If you are still encountering any issues, please open an issue on https://github.com/polymerelements/polymer-starter-kit
