### ISSUE TITLE
polymer init is not working please help me

### ISSUE THREAD

**Issue by karangoswami31** [Polymer/polymer#4094]
D:\3rd>polymer init
'uname' is not recognized as an internal or external command,
operable program or batch file.
? Which starter template would you like to use? shop
info:    Running template shop...
info:    Downloading latest release of Polymer/shop
error:   Could not download release from Polymer/shop
error:   Uncaught exception: unable to verify the first certificate
error:   Error: **# unable to verify the first certificate**
    at __dirname.sendError (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:780:19)
    at C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:789:29
    at callCallback (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:665:17)
    at ClientRequest.<anonymous> (C:\Users\karan\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:737:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)

**Comment by TimvdLippe** [comment]
Please ask such questions on the Polymer Slack (https://polymer-slack.herokuapp.com/) or on Stackoverflow (http://stackoverflow.com/questions/tagged/polymer)

**Comment by kevinpschaaf** [comment]
This issue was moved to Polymer/polymer-cli#450
