### ISSUE TITLE
polymer starter kit 2 based project errors after update to polymer 2.0.0-rc2

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/polymer#4403]
#### Steps to Reproduce
after an update of my psk2 project to polymer 2.0.0-rc2 from 1.8.1 it doesn't load with an error.
polymer-build gives an error as well

#### Expected Results
No error

#### Actual Results
polymer serve and following error occurs in browser
```
Uncaught TypeError: this._debounceTemplate is not a function
    at HTMLElement._setOverflow (iron-list.html:801)
    at Object.runMethodEffect [as fn] (property-effects.html:900)
    at runEffectsForProperty (property-effects.html:127)
    at runEffects (property-effects.html:100)
    at HTMLElement._propertiesChanged (property-effects.html:1735)
    at HTMLElement._flushProperties (property-accessors.html:443)
    at HTMLElement._flushProperties (property-effects.html:1629)
    at HTMLElement.ready (property-effects.html:1663)
    at HTMLElement.ready (legacy-element-mixin.html:135)
    at HTMLElement.ready (class.html:201)


_setOverflow	@	iron-list.html:801
runMethodEffect	@	property-effects.html:900
runEffectsForProperty	@	property-effects.html:127
runEffects	@	property-effects.html:100
_propertiesChanged	@	property-effects.html:1735
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
ready	@	property-effects.html:1663
ready	@	legacy-element-mixin.html:135
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
_flushProperties	@	property-effects.html:1627
connectedCallback	@	element-mixin.html:607
connectedCallback	@	legacy-element-mixin.html:70
_attachDom	@	element-mixin.html:653
_readyClients	@	element-mixin.html:630
_flushClients	@	property-effects.html:1576
_propertiesChanged	@	property-effects.html:1731
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
ready	@	property-effects.html:1663
ready	@	legacy-element-mixin.html:135
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
_flushProperties	@	property-effects.html:1627
_flushClients	@	property-effects.html:1585
_propertiesChanged	@	property-effects.html:1731
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
runNotifyEffects	@	property-effects.html:223
_propertiesChanged	@	property-effects.html:1738
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
_invalidateProperties	@	property-effects.html:1549
_setProperty	@	property-effects.html:1535
Object.defineProperty.set	@	property-accessors.html:356
_updateAttrForSelected	@	iron-selectable.html:279
runMethodEffect	@	property-effects.html:900
runEffectsForProperty	@	property-effects.html:127
runEffects	@	property-effects.html:100
_propertiesChanged	@	property-effects.html:1735
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
ready	@	property-effects.html:1663
ready	@	legacy-element-mixin.html:135
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
_flushProperties	@	property-effects.html:1627
connectedCallback	@	element-mixin.html:607
connectedCallback	@	legacy-element-mixin.html:70
_attachDom	@	element-mixin.html:653
_readyClients	@	element-mixin.html:630
_flushClients	@	property-effects.html:1576
_propertiesChanged	@	property-effects.html:1731
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
ready	@	property-effects.html:1663
ready	@	legacy-element-mixin.html:135
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
ready	@	class.html:201
_flushProperties	@	property-effects.html:1627
connectedCallback	@	element-mixin.html:607
connectedCallback	@	legacy-element-mixin.html:70
_attachDom	@	element-mixin.html:653
_readyClients	@	element-mixin.html:630
_flushClients	@	property-effects.html:1576
_propertiesChanged	@	property-effects.html:1731
_flushProperties	@	property-accessors.html:443
_flushProperties	@	property-effects.html:1629
ready	@	property-effects.html:1663
ready	@	legacy-element-mixin.html:135
ready	@	class.html:201
_flushProperties	@	property-effects.html:1627
connectedCallback	@	element-mixin.html:607
connectedCallback	@	legacy-element-mixin.html:70
window.Polymer._polymerFn	@	polymer-fn.html:41
window.Polymer	@	boot.html:23
(anonymous)	@	my-app.html:106

```

polymer-build throws a following error:
```
error:   Promise rejection: Error: Error parsing script in bower_components/polymer/lib/legacy/class.html at NaN:NaN
TypeError: Cannot read property 'forEach' of undefined
    at Object.enterMethodDefinition (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/element-finder.js:92:38)
    at applyVisitors (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:31:51)
    at Controller.enter (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:54:20)
    at Controller.__execute (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:395:31)
    at Controller.traverse (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:493:28)
    at Object.traverse (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:705:27)
    at Object.jsParse (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:75:16)
    at Analyzer._processScript (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:318:43)
    at /home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
error:   Error: Error parsing script in bower_components/polymer/lib/legacy/class.html at NaN:NaN
TypeError: Cannot read property 'forEach' of undefined
    at Object.enterMethodDefinition (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/element-finder.js:92:38)
    at applyVisitors (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:31:51)
    at Controller.enter (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:54:20)
    at Controller.__execute (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:395:31)
    at Controller.traverse (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:493:28)
    at Object.traverse (/home/user/Documents/psk2/node_modules/hydrolysis/node_modules/estraverse/estraverse.js:705:27)
    at Object.jsParse (/home/user/Documents/psk2/node_modules/hydrolysis/lib/ast-utils/js-parse.js:75:16)
    at Analyzer._processScript (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:318:43)
    at /home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScript (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:331:36)
    at /home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (/home/user/Documents/psk2/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
### Browsers Affected

- [x ] Chrome

### Versions

- Polymer: v2.0.0-rc2
- webcomponents: v1.0.0-rc5

**Comment by azakus** [comment]
This issue was moved to PolymerElements/polymer-starter-kit#983
