### ISSUE TITLE
[Polymer 3.0] Declaring class inside function makes `polymer build` fail.

### ISSUE THREAD

**Issue by kkimdev** [Polymer/polymer#5005]
### Description
On Polymer 3.0, declaring class inside function makes `polymer build` fail.

#### Steps to Reproduce

1. Follow https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview
2. edit myapp.js so that
```javascript
// ...
  constructor() {
    super();
    class Foo{};
    this.name = '3.0 preview';
  }
// ...
```

#### Expected Results
`polymer build` succeeds.

#### Actual Results
`polymer build` fails.
```
polymer build
info:    Clearing build/ directory...
info:    (default) Building...


    <script type="module" src="src/my-app.js"></script>
                              ~~~~~~~~~~~~~~~

index.html(9,30) error [could-not-load] - Unable to load import: Cannot read property 'properties' of null
error:   Promise rejection: Error: 1 error(s) occurred during build.
error:   Error: 1 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:262:36)
    at BuildAnalyzer.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:222:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:17:58)
    at <anonymous>
```

### Versions
$ polymer --version
1.5.7

**Comment by kkimdev** [comment]
@farQtech

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/polymer-analyzer#832
