### ISSUE TITLE
Travis PR build has been failing lately

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#5336]
On our PRs, we have not had a single full green build lately. In particular, the Travis "PR" job errors, while the "Push" job is fine. (Note that the Push build actually runs on Sauce, so we are still okay on older browsers).

The builds show the following error:

```
$ node ./node_modules/.bin/polymer test --npm --module-resolution=node -l firefox
Installing and starting Selenium server for local browsers
Selenium server running on port 42773
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
firefox 61               Beginning tests via http://localhost:8081/components/@polymer/polymer/generated-index.html?cli_browser_id=0
firefox 61               Tests failed: Timed out
firefox 61               Failed to quit: {"message":"[quit()] Error response status: 33 Selenium error: Tried to run command without establishing a connection\nBuild info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'\nSystem info: host: 'travis-job-polymer-polymer-418334737', ip: '172.17.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.12-041412-generic', java.version: '1.8.0_151'\nDriver info: driver.version: unknown","status":33,"cause":{"sessionId":null,"state":"session not created","hCode":188...
Test run ended in failure: Timed out
firefox 61 (113/0/0 error)            
Error: Timed out
error: [cli.main]   cli runtime exception: Error: Timed out
error: [cli.main]   Error: Timed out
    at /home/travis/build/Polymer/polymer/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:170:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/Polymer/polymer/node_modules/polymer-cli/node_modules/web-component-tester/runner/steps.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
The command "node ./node_modules/.bin/polymer test --npm --module-resolution=node -l firefox"
```

We have been manually restarting these builds, to get over this Firefox hickup. Chrome seems to be working just fine.

To limit the chance that Selenium fails twice in a row, could we maybe run Chrome and Firefox with the same command again? E.g. `node ./node_modules/.bin/polymer test --npm --module-resolution=node -l firefox -l chrome`

**Comment by kevinpschaaf** [comment]
It always seems to be around test 100 +/- 10 or so... Haven't gotten it to timeout locally like that.
