### ISSUE TITLE
AngularJS/Polymer 1.x/Webcomponents broken in Canary

### ISSUE THREAD

**Issue by rgb4268** [Polymer/polymer#5619]
I have an Angular 1.3 app running. It works fine on Chrome. However, it does not render correctly in Canary v80. The following are snippets from my code -

<paper-dropdown-menu > <paper-listbox class="dropdown-content" selected = "1"> <paper-menu class="menu" data-ng-model="abc" attr-for-selected="name"> <paper-item name="{{a}}" data-ng-repeat="a in abc">{{a}}</paper-item> </paper-menu> </paper-listbox> </paper-dropdown-menu>
(This works fine if the data is something static)

In the controller file, I invoke a REST call to get the data 'abc'. I have verified by the debugger that the data is loaded correctly.

In the drop-down, nothing shows. So data-ng-model is not loading data in time for the render. I get the stack trace below
TypeError: el.getPropertyInfo is not a function
at http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:196:39
at Array.forEach ()
at link (http://127.0.0.1:9000/bower_components/ng-polymer-elements/ng-polymer-elements.js:163:18)
...
at compositeLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:7143:13)

I don't know where this error is coming from.

**Comment by bicknellr** [comment]
Given that your app starts failing specifically in Chrome 80 and it looks like you're using Polymer 1 (because bower), you're probably not loading the polyfills. The older version of the specs (v0) are being [removed in Chrome 80](https://developers.google.com/web/updates/2019/12/chrome-80-deps-rems#web_components_v0_removed), which is expected to roll out next month. You can check out [this article](https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade) for more instructions on how to prepare for this deprecation.

**Comment by kobee-tech-stack** [comment]
Yah. I also have the same situation with Polymer 1.9.

My project works well with chrome version 79.x.
However team's member update chrome to version 80.x.

{{data}} have a problem: The UI not loading data. ( I don't know the reason why: ¯\_(ツ)_/¯ )

**Solution:**
I make sure data ready from REST API & using dom-if to work around.
