### ISSUE TITLE
paper-dialog 0.3.5: Exception caught during observer callback: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ubs121** [Polymer/polymer#701]
When paper-dialog element inserted into DOM the following error comes. May be it's related to paper-shadow component.

Exception caught during observer callback: TypeError: undefined is not a function
    at core-overlay.Polymer.addElementListener (http://localhost/web/bower_components/core-overlay/core-overlay.html:565:17)
    at core-overlay.Polymer.addElementListenerList (http://localhost/web/bower_components/core-overlay/core-overlay.html:544:14)
    at core-overlay.Polymer.targetChanged (http://localhost/web/bower_components/core-overlay/core-overlay.html:264:14)
    at core-overlay.g.invokeMethod (http://localhost/web/bower_components/polymer/polymer.js:12:12916)
    at core-overlay.g.notifyPropertyChanges (http://localhost/web/bower_components/polymer/polymer.js:12:11202)
    at Object.Observer.report_ (http://localhost/web/bower_components/platform/platform.js:12:12814)
    at Object.createObject.check_ (http://localhost/web/bower_components/platform/platform.js:12:18305)
    at c (http://localhost/web/bower_components/platform/platform.js:12:5610) observe.js:769Observer.report_ observe.js:769createObject.check_ observe.js:1186c

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
