### ISSUE TITLE
Vulcanize should ignore non-existent files

### ISSUE THREAD

**Issue by viridium** [Polymer/polymer#819]
Vulcanize should be more resilient to non-existent files. It currently bails on errors.

```
bower-components/vis/examples/graph3d/playground/csv2datatable.html

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '.../bower-components/vis/examples/graph3d/playground/default.css'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at readFile (/usr/local/lib/node_modules/vulcanize/lib/vulcan.js:57:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/vulcanize/lib/vulcan.js:70:81)
    at exports.each (/usr/local/lib/node_modules/vulcanize/node_modules/cheerio/lib/api/traversing.js:268:24)
    at inlineSheets (/usr/local/lib/node_modules/vulcanize/lib/vulcan.js:64:31)
    at Object.handleMainDocument [as processDocument] (/usr/local/lib/node_modules/vulcanize/lib/vulcan.js:179:5)
    at /usr/local/lib/node_modules/vulcanize/bin/vulcanize:74:10
    at /usr/local/lib/node_modules/vulcanize/lib/vulcan.js:34:5
    at Object.processOptions (/usr/local/lib/node_modules/vulcanize/lib/optparser.js:78:3)
Error at components/vis/examples/graph3d/playground/datasource.html.
```

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
